import type { Metadata } from "next";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Container, Theme, ThemePanel } from "@radix-ui/themes";
import Navbar from "./NavBar";
import { Roboto } from "next/font/google";
import SessionProvider from "@/app/auth/SessionProvider";

const roboto = Roboto({
  weight: ["700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Issue Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <SessionProvider>
          <Theme accentColor="iris">
            <main className="border border-zinc-400">
              <Navbar />
            </main>
            <main className="p-5">
              <Container>{children}</Container>
            </main>
          </Theme>
        </SessionProvider>
      </body>
    </html>
  );
}
