import type { Metadata } from "next";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Container, Theme, ThemePanel } from "@radix-ui/themes";
import Navbar from "./NavBar";
import { Roboto } from "next/font/google";
import SessionProvider from "@/app/auth/SessionProvider";
import QueryClientProvider from "./QueryClientProvider";

const roboto = Roboto({
  weight: ["700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Issue Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <QueryClientProvider>
          <SessionProvider>
            <Theme accentColor="iris">
              <div className="shadow-lg">
                <Navbar />
              </div>

              <main className="p-7">
                <Container>{children}</Container>
              </main>
            </Theme>
          </SessionProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
